# NOTE conventionally, service names and container_names are the same modulo
# s/_/-/g.  This convention is used by the Makefile to automate the process of
# gathering the node names and creating targets for interactive shells.
#
# TODO order network attachments right-to-left (or viceversa, but in a
# consistent way) so that we can make safe assumptions on the naming of the
# interfaces when applying queueing disciplines.
version: '3'

services:
  # Traffic generator in the (S)Gi-LAN
  tg_sgilan:
    build:
      context: nodes/tg_sgilan
    entrypoint: /root/entrypoint.sh ${PGW_SGILAN_ADDR} ${RAN_SUBNET} "tg-sgilan"
    container_name: tg-sgilan
    networks:
      sgilan:
        ipv4_address: ${TG_SGILAN_ADDR}
    extra_hosts:
      - "tg-mobile:${TG_RAN_ADDR}" 
      - "sut-mobile:${SUT_RAN_ADDR}" 
      - "pcap-mobile:${PCAP_RAN_ADDR}"
    volumes:
      - ./volumes/scripts:/root/scripts
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # System Under Test (SUT) in the (S)Gi-LAN
  sut_sgilan:
    build:
      context: nodes/sut_sgilan
    entrypoint: /root/entrypoint.sh ${PGW_SGILAN_ADDR} ${RAN_SUBNET} "sut-sgilan"
    container_name: sut-sgilan
    networks:
      sgilan:
        ipv4_address: ${SUT_SGILAN_ADDR}
    extra_hosts:
      - "tg-mobile:${TG_RAN_ADDR}"
      - "sut-mobile:${SUT_RAN_ADDR}"
      - "pcap-mobile:${PCAP_RAN_ADDR}"
    volumes:
      - ./volumes/scripts:/root/scripts
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # eNB downstream scheduler in the eNB/PGW super-node
  enb_downstream_sched:
    build:
      context: nodes/enb_downstream_sched
    entrypoint: /root/entrypoint.sh ${RAN_SUBNET} ${ENB_TRAFFIC_SHAPER_NORTH_ADDR} "enb-downstream-sched"
    container_name: enb-downstream-sched
    networks:
      sgilan:
        aliases:
          - pgw-sgilan
        ipv4_address: ${PGW_SGILAN_ADDR}
      enb-north:
        ipv4_address: ${ENB_DOWNSTREAM_SCHED_NORTH_ADDR}
    volumes:
      - ./volumes/scripts:/root/scripts
    sysctls:
      net.ipv4.ip_forward: 1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # eNB traffic shaper in the eNB/PGW super-node (enforces up and downstream
  # bandwidth and latency)
  enb_traffic_shaper:
    build:
      context: nodes/enb_traffic_shaper
    entrypoint: /root/entrypoint.sh ${SGILAN_SUBNET} ${ENB_DOWNSTREAM_SCHED_NORTH_ADDR} ${RAN_SUBNET} ${ENB_UPSTREAM_SCHED_SOUTH_ADDR} "enb-traffic-shaper"
    container_name: enb-traffic-shaper
    networks:
      enb-north:
        ipv4_address: ${ENB_TRAFFIC_SHAPER_NORTH_ADDR}
      enb-south:
        ipv4_address: ${ENB_TRAFFIC_SHAPER_SOUTH_ADDR}
    volumes:
      - ./volumes/scripts:/root/scripts
    sysctls:
      net.ipv4.ip_forward: 1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # eNB upstream scheduler in the eNB/PGW super-node
  enb_upstream_sched:
    build:
      context: nodes/enb_upstream_sched
    entrypoint: /root/entrypoint.sh ${SGILAN_SUBNET} ${ENB_TRAFFIC_SHAPER_SOUTH_ADDR} "enb-upstream-sched"
    container_name: enb-upstream-sched
    networks:
      ran:
        ipv4_address: ${ENB_RAN_ADDR}
      enb-south:
        ipv4_address: ${ENB_UPSTREAM_SCHED_SOUTH_ADDR}
    volumes:
      - ./volumes/scripts:/root/scripts
    sysctls:
      net.ipv4.ip_forward: 1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # System Under Test (SUT) in the RAN
  sut_mobile:
    build:
      context: nodes/sut_mobile
    entrypoint: /root/entrypoint.sh ${ENB_RAN_ADDR} ${SGILAN_SUBNET} "sut-mobile"
    container_name: sut-mobile
    networks:
      ran:
        ipv4_address: ${SUT_RAN_ADDR}
    extra_hosts:
      - "tg-sgilan:${TG_SGILAN_ADDR}" 
      - "sut-sgilan:${SUT_SGILAN_ADDR}" 
    volumes:
      - ./volumes/scripts:/root/scripts
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # Traffic generator in the RAN
  tg_mobile:
    build:
      context: nodes/tg_mobile
    entrypoint: /root/entrypoint.sh ${ENB_RAN_ADDR} ${SGILAN_SUBNET} "tg-mobile"
    container_name: tg-mobile
    networks:
      ran:
        ipv4_address: ${TG_RAN_ADDR}
    extra_hosts:
      - "tg-sgilan:${TG_SGILAN_ADDR}" 
      - "sut-sgilan:${SUT_SGILAN_ADDR}" 
    volumes:
      - ./volumes/scripts:/root/scripts
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

#   # Packet capture node in the RAN 
#   pcap_mobile:
#     build:
#       context: nodes/pcap_mobile
#     entrypoint: /root/entrypoint.sh "pcap-mobile"
#     container_name: pcap-mobile
#     networks:
#       ran:
#         ipv4_address: ${PCAP_RAN_ADDR}
#     extra_hosts:
#       - "tg-sgilan:${TG_SGILAN_ADDR}" 
#       - "sut-sgilan:${SUT_SGILAN_ADDR}" 
#       - "pgw:${PGW_CORE_ADDR}" 
#     volumes:
#       - ./volumes/captures:/tmp/captures
#     cap_add:
#       - NET_ADMIN
#       - SYS_ADMIN
#     stdin_open: true
#     tty: true

networks:
  ran:
    ipam:
      config:
        - subnet: ${RAN_SUBNET}
  enb-north:
    ipam:
      config:
        - subnet: ${ENB_NORTH_SUBNET}
  enb-south:
    ipam:
      config:
        - subnet: ${ENB_SOUTH_SUBNET}
  sgilan:
    ipam:
      config:
        - subnet: ${SGILAN_SUBNET}

# vim: ai ts=2 sw=2 et sts=2 ft=yaml
