# See also:
#   - depends_on and healthcheck for modelling dependencies
#   - logging to specify how to log (e.g. syslog) and where is your log sink
#   - sysctls and ulimits to change kernel/runtime settings
version: '3'

services:
  # Traffic generator in the (S)Gi-LAN
  tg_inet:
    build:
      context: nodes/tg_inet
    entrypoint: /root/entrypoint.sh ${PGW_INET_ADDR} ${CORE_SUBNET} ${RAN_SUBNET} "tg-inet"
    container_name: tg-inet
    networks:
      sgilan:
        ipv4_address: ${TG_INET_ADDR}
    extra_hosts:
      - "tg-mobile:${TG_RAN_ADDR}" 
      - "sut-mobile:${SUT_RAN_ADDR}" 
      - "pcap-mobile:${PCAP_RAN_ADDR}"
      - "enb:${ENB_CORE_ADDR}" 
    volumes:
      - ./volumes/scripts:/root/scripts
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # System Under Test (SUT) in the (S)Gi-LAN
  sut_inet:
    build:
      context: nodes/sut_inet
    entrypoint: /root/entrypoint.sh ${PGW_INET_ADDR} ${CORE_SUBNET} ${RAN_SUBNET} "sut-inet"
    container_name: sut-inet
    networks:
      sgilan:
        ipv4_address: ${SUT_INET_ADDR}
    extra_hosts:
      - "tg-mobile:${TG_RAN_ADDR}"
      - "sut-mobile:${SUT_RAN_ADDR}"
      - "pcap-mobile:${PCAP_RAN_ADDR}"
      - "enb:${ENB_CORE_ADDR}"
    volumes:
      - ./volumes/scripts:/root/scripts
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # Packet gateway, bridging (S)Gi-LAN and mobile packet core
  pgw:
    build:
      context: nodes/pgw
    entrypoint: /root/entrypoint.sh ${RAN_SUBNET} ${ENB_CORE_ADDR} ${PGW_CORE_ADDR} "pgw"
    container_name: pgw
    networks:
      sgilan:
        aliases:
          - pgw-inet
        ipv4_address: ${PGW_INET_ADDR}
      core:
        aliases:
          - pgw-core
        ipv4_address: ${PGW_CORE_ADDR}
    extra_hosts:
      - "tg-mobile:${TG_RAN_ADDR}"
      - "sut-mobile:${SUT_RAN_ADDR}"
      - "pcap-mobile:${PCAP_RAN_ADDR}"
    volumes:
      - ./volumes/scripts:/root/scripts
    sysctls:
      net.ipv4.ip_forward: 1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # ENodeB, bridging mobile packet core and RAN
  enb:
    build:
      context: nodes/enb
    entrypoint: /root/entrypoint.sh ${SGILAN_SUBNET} ${PGW_CORE_ADDR} ${ENB_CORE_ADDR} "enb"
    env_file: .env
    container_name: enb
    networks:
      core:
        aliases:
          - enb-core
        ipv4_address: ${ENB_CORE_ADDR}
      ran:
        aliases:
          - enb-ran
        ipv4_address: ${ENB_RAN_ADDR}
    extra_hosts:
      - "tg-inet:${TG_INET_ADDR}" 
      - "sut-inet:${SUT_INET_ADDR}" 
    volumes:
      - ./volumes/scripts:/root/scripts
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      net.ipv4.ip_forward: 1
    stdin_open: true
    tty: true

  # System Under Test (SUT) in the RAN
  sut_mobile:
    build:
      context: nodes/sut_mobile
    entrypoint: /root/entrypoint.sh ${ENB_RAN_ADDR} ${CORE_SUBNET} ${SGILAN_SUBNET} "sut-mobile"
    container_name: sut-mobile
    networks:
      ran:
        ipv4_address: ${SUT_RAN_ADDR}
    extra_hosts:
      - "tg-inet:${TG_INET_ADDR}" 
      - "sut-inet:${SUT_INET_ADDR}" 
      - "pgw:${PGW_CORE_ADDR}" 
    volumes:
      - ./volumes/scripts:/root/scripts
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # Traffic generator in the RAN
  tg_mobile:
    build:
      context: nodes/tg_mobile
    entrypoint: /root/entrypoint.sh ${ENB_RAN_ADDR} ${CORE_SUBNET} ${SGILAN_SUBNET} "tg-mobile"
    container_name: tg-mobile
    networks:
      ran:
        ipv4_address: ${TG_RAN_ADDR}
    extra_hosts:
      - "tg-inet:${TG_INET_ADDR}" 
      - "sut-inet:${SUT_INET_ADDR}" 
      - "pgw:${PGW_CORE_ADDR}" 
    volumes:
      - ./volumes/scripts:/root/scripts
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  # Packet capture node in the RAN 
  pcap_mobile:
    build:
      context: nodes/pcap_mobile
    entrypoint: /root/entrypoint.sh "pcap-mobile"
    container_name: pcap-mobile
    networks:
      ran:
        ipv4_address: ${PCAP_RAN_ADDR}
    extra_hosts:
      - "tg-inet:${TG_INET_ADDR}" 
      - "sut-inet:${SUT_INET_ADDR}" 
      - "pgw:${PGW_CORE_ADDR}" 
    volumes:
      - ./volumes/captures:/tmp/captures
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

networks:
  ran:
    ipam:
      config:
        - subnet: ${RAN_SUBNET}
  core:
    ipam:
      config:
        - subnet: ${CORE_SUBNET}
  sgilan:
    ipam:
      config:
        - subnet: ${SGILAN_SUBNET}

# vim: ai ts=2 sw=2 et sts=2 ft=yaml
